[package]
name = "cloaked_req_native"
version = "0.4.0"
edition = "2024"
rust-version = "1.91"

[lib]
name = "cloaked_req_native"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.37.4", default-features = false, features = ["derive", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "net", "time"] }
futures-util = "0.3"
wreq = { version = "6.0.0-rc.29", features = ["hickory-dns", "gzip", "brotli", "zstd", "deflate", "cookies", "stream"] }
http = "1"
psl = "2"
wreq-util = { version = "3.0.0-rc.12", features = ["emulation-serde"] }

[lints.rust]
unsafe_code = "forbid"

[features]
default = ["nif_version_2_17"]
nif_version_2_17 = ["rustler/nif_version_2_17"]
